# Generated by Django 5.1.7 on 2025-03-30 19:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_emailverificationtoken_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='technicianprofile',
            name='experience_years',
        ),
        migrations.AddField(
            model_name='technicianprofile',
            name='experience',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='technicianprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='technicianprofile', to=settings.AUTH_USER_MODEL),
        ),
    ]
